TITLE_1: SEL0617
TITLE_2: Fundamentos de Microeletrônica
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SEL0617-Fundamentos-Microeletronica
HERO_FILE: fundamentos-microeletronica.png